from __future__ import annotations

from enum import StrEnum


class CollectionStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    QUEUED = "QUEUED"
    FETCH_ATTEMPTED = "FETCH_ATTEMPTED"
    FETCHED = "FETCHED"
    PARSED = "PARSED"
    NORMALIZED = "NORMALIZED"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    DEAD = "DEAD"
    MALFORMED = "MALFORMED"
    RETRYABLE_FAILURE = "RETRYABLE_FAILURE"
    FINAL_FAILURE = "FINAL_FAILURE"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"


class SourceContentStatus(StrEnum):
    REFERENCE_ONLY = "REFERENCE_ONLY"
    URL_PRESERVED = "URL_PRESERVED"
    METADATA_ONLY = "METADATA_ONLY"
    PARTIAL_TEXT = "PARTIAL_TEXT"
    FULL_TEXT_DIRECT = "FULL_TEXT_DIRECT"
    FULL_TEXT_ARCHIVED = "FULL_TEXT_ARCHIVED"
    FULL_TEXT_LOCAL_SNAPSHOT = "FULL_TEXT_LOCAL_SNAPSHOT"
    BLOCKED = "BLOCKED"
    DEAD = "DEAD"
    MALFORMED = "MALFORMED"
    RESTRICTED = "RESTRICTED"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"


class RunStatus(StrEnum):
    CREATED = "CREATED"
    ANALYZING = "ANALYZING"
    PILOT_RUNNING = "PILOT_RUNNING"
    PILOT_REVIEW = "PILOT_REVIEW"
    READY = "READY"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    RETRYING = "RETRYING"
    VALIDATING = "VALIDATING"
    BUILDING_RELEASE = "BUILDING_RELEASE"
    RELEASE_VALIDATION = "RELEASE_VALIDATION"
    PUBLISHED = "PUBLISHED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_GAPS = "COMPLETED_WITH_GAPS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


TERMINAL_RUN_STATUSES = {
    RunStatus.PUBLISHED,
    RunStatus.COMPLETED,
    RunStatus.COMPLETED_WITH_GAPS,
    RunStatus.FAILED,
    RunStatus.CANCELLED,
}
